# Generated by Django 3.0.8 on 2020-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200901_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='内容')),
                ('icon', models.CharField(default='images/tx1.jpg', max_length=150, verbose_name='头像')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言表',
                'verbose_name_plural': '留言表',
                'db_table': 'message',
            },
        ),
    ]
